package com.wellpoint.mde.constants;

import java.util.Arrays;
import java.util.List;

public enum OrgEnum {

	EPDSV2ORG("EPDSV2ORG"),
	QCAREORG("QCAREORG"),
	EPDSV2("EPDSV2"),
	EPDS1ORG("EPDS1ORG"),
	EPDS1("EPDS1"),
	WMSORG("WMSORG"),
	WMS("WMS"),
	ORGRMB("ORGRMB"),
	ORGNTWRK("ORGNTWRK"),
	ORGRSKWTHLD("ORGRSKWTHLD"),
	ORGTYPCD("ORGTYPCD"),
	ORGCATEGORY("ORGCATEGORY"),
	REMPAYIND("REMPAYIND"),
	ORGTYPE("ORGTYPE"),
	ORGNPIELIG("ORGNPIELIG"),
	ORGPARIND("ORGPARIND"),
	ORGCACTUSFCL("ORGCACTUSFCL"),
	ORGGBDCD("ORGGBDCD"),
	ORGNTYPE("ORGNTYPE"),
	ORGATTEST("ORGATTEST"),
	ORGCREDSTAT("ORGCREDSTAT"),
	ORGRANK("ORGRANK"),
	ORGDIST("ORGDIST"),
	BILLFORM("BILLFORM"),
	ORGNOTE("ORGNOTE"),
	SANCTIONORG("SANCTIONORG"),
	ORGSANCCLACT("ORGSANCCLACT"),
	OFFSTFLNGORG("OFFSTFLNGORG"),
	ORGSPECPRG("ORGSPECPRG"),
	SPLTYSVCORG("SPLTYSVCORG"),
	ORGEXPRTAREA("ORGEXPRTAREA"),
	ORGPRCOFCSVC("ORGPRCOFCSVC"),
	ORGDBANAME("ORGDBANAME"),
	ORGCONTACT("ORGCONTACT"),
	ORGCNTCTNA("ORGCNTCTNA"),
	OFFPTLIMORG("OFFPTLIMORG"),
	SCHEDORG("SCHEDORG"),
	OFFTECHORG("OFFTECHORG"),
	OFFACCORG("OFFACCORG"),
	OFFRSTRCTSVC("OFFRSTRCTSVC"),
	SERVLOCORG("SERVLOCORG"),
	ORGCORRLOC("ORGCORRLOC"),
	ORGREMITLOC("ORGREMITLOC"),
	ORG1099ADDR("ORG1099ADDR"),
	ORGBILLADDR("ORGBILLADDR"),
	ORGCAPADDR("ORGCAPADDR"),
	ORGCSAADDR("ORGCSAADDR"),
	ORGADDRNA("ORGADDRNA"),
	ORGCAPCKADDR("ORGCAPCKADDR"),
	ORGPAYINADDR("ORGPAYINADDR"),
	ORGHMORELADR("ORGHMORELADR"),
	ORGFACSTERE("ORGFACSTERE"),
	ORGROLLID("ORGROLLID"),
	ORGREGN("ORGREGN"),
	TAXIDORG("TAXIDORG"),
	ORGBUSENTREL("ORGBUSENTREL"),
	ORGCNTRCT("ORGCNTRCT"),
	ORGGRPCTRCT("ORGGRPCTRCT"),
	ORGWREL("ORGWREL"),
	ORGGRPNET("ORGGRPNET"),
	ORGHMOCNTREL("ORGHMOCNTREL"),
	SERVCNTCORG("SERVCNTCORG"),
	ORGCORRLOCCT("ORGCORRLOCCT"),
	REMITCNTCORG("REMITCNTCORG"),
	ORGCSACNTCT("ORGCSACNTCT"),
	ORGPAYINCNTC("ORGPAYINCNTC"),
	ORGCAPCKCNTC("ORGCAPCKCNTC"),
	ORG1099CNTCT("ORG1099CNTCT"),
	ORGBILLCNTCT("ORGBILLCNTCT"),
	ORGCAPCNTCT("ORGCAPCNTCT"),
	INACTIVEORG("INACTIVEORG"),
	ORGNAME("ORGNAME"),
	ORGACESLGCY("ORGACESLGCY"),
	ORGCPFLGCY("ORGCPFLGCY"),
	ORGCPMFLGCY("ORGCPMFLGCY"),
	ORGEPSBLGCY("ORGEPSBLGCY"),
	ORGQCARELGCY("ORGQCARELGCY"),
	ORGPADRLGCY("ORGPADRLGCY"),
	ORGFACHSANET("ORGFACHSANET"),
	ORGREL("ORGREL"),
	TAXNMYORG("TAXNMYORG"),
	ORGGRPMEM("ORGGRPMEM"),
	REMITSEG("REMITSEG"),
	REMITSEGDTL("REMITSEGDTL"),
	ORGBRDCRT("ORGBRDCRT"),
	SPLTYTXNMORG("SPLTYTXNMORG"),
	ORGCLAIMACT("ORGCLAIMACT"),
	ALTSYSIDSORG("ALTSYSIDSORG"),
	NPIORG("NPIORG"),
	UPINORG("UPINORG"),
	MEDICAREORG("MEDICAREORG"),
	MEDICAIDORG("MEDICAIDORG"),
	ENCLRTYIDORG("ENCLRTYIDORG"),
	LICENSEORG("LICENSEORG"),
	ORGALTIDSPEC("ORGALTIDSPEC"),
	ORGDIRDISIND("ORGDIRDISIND"),
	ORGDATAMANG("ORGDATAMANG"),
	
	EMEMADDR("EMEMADDR"),
	EMEMREL("EMEMREL"),
	EMEMIDENT("EMEMIDENT"),
	EMEMLICENSE("EMEMLICENSE"),
	EMEMIDSPEC("EMEMIDSPEC"),
	EMEMSPLTYBRD("EMEMSPLTYBRD"),
	EMEMSPTYTXNM("EMEMSPTYTXNM"),
	EMEMRMB("EMEMRMB"),
	EMEMNET("EMEMNET"),
	EMEMRSKWIHLD("EMEMRSKWIHLD"),
	EMEMGRPREL("EMEMGRPREL"),
	EMEMCLAIMACT("EMEMCLAIMACT"),
	EMEMTAXNMY("EMEMTAXNMY"),
	MEMATTR("MEMATTR"),
	EMEMATRCDTMD("EMEMATRCDTMD"),
	EMEMEPDSLGCY("EMEMEPDSLGCY"),
	EMEMQCARELGY("EMEMQCARELGY"),
	EMEMACESLGCY("EMEMACESLGCY"),
	EMEMCPFLGCY("EMEMCPFLGCY"),
	EMEMCPMFLGCY("EMEMCPMFLGCY"),
	EMEMATRCODE("EMEMATRCODE"),
	EMEMREMIT("EMEMREMIT"),
	EMEMREMITDTL("EMEMREMITDTL"),
	
	/*------------Segment Name----------*/
	APDM("APDM"),
	QCARE_APADR("QCARE_APADR"),
	NASCOPCNTC("NASCOPCNTC"),
	APADR("APADR"),
	APCNTC("APCNTC"),
	APGREL("APGREL"),
	APREL("APREL"),
	PNET("PNET"),
	PRMB("PRMB"),
	
	ALTSRCID("ALTSRCID"),
	APALT("APALT"),
	APCLMACT("APCLMACT"),
	APREM("APREM"),
	APSPT("APSPT"),
	APTXN("APTXN"),
	GNET("GNET"),
	GRMB("GRMB"),
	PADR("PADR"),
	PALT("PALT"),
	PALTROL("PALTROL"),
	PAOF("PAOF"),
	PATTS("PATTS"),
	PBREL("PBREL"),
	PCLMACT("PCLMACT"),
	PCLMFRM("PCLMFRM"),
	PCNTC("PCNTC"),
	PCRED("PCRED"),
	PDBA("PDBA"),
	PDSTC("PDSTC"),
	PGREL("PGREL"),
	PNOTE("PNOTE"),
	POCON("POCON"),
	POFACS("POFACS"),
	POFSCH("POFSCH"),
	POFSR("POFSR"),
	POFSRR("POFSRR"),
	POFTCH("POFTCH"),
	POT("POT"),
	PPGM("PPGM"),
	PPPRF("PPPRF"),
	PREL("PREL"),
	PREM("PREM"),
	PRF("PRF"),
	PRGN("PRGN"),
	PRNK("PRNK"),
	PSANC("PSANC"),
	PSNAC("PSNAC"),
	PSPT("PSPT"),
	PSTFLANG("PSTFLANG"),
	PTXN("PTXN"),
	PTAX("PTAX"),
	PWTH("PWTH"),
	WCON("WCON"),
	WREL("WREL"),
	
	DEFAULT("DEFAULT");
	
	private String value;
	
	/**
	 * Instantiates a new MemGetEnum enum.
	 *
	 * @param value the value
	 */
	private OrgEnum(final String value) {
		this.value = value;
	}	
	
	/**
	 * Gets the MemGetEnum constants.
	 *
	 * @return the MemGetEnum constants
	 */
	public static List<OrgEnum> getInitiateConstants() {
		return Arrays.asList(OrgEnum.values());
	}

	/**
	 * Gets the value.
	 *
	 * @return the value
	 */
	public final String getValue() {
		return value;
	}

	@Override
	public final String toString() {
		return this.getValue();
	}	

	/**
	 * Gets the initiate enum.
	 *
	 * @param value the value
	 * @return the MemGetEnum enum
	 */
	public static OrgEnum getInitiateEnum(final String value) {
		OrgEnum returnValue = DEFAULT;
		for (OrgEnum orgEnum : values()) {
			if (orgEnum.value.equals(value)) {
				returnValue = orgEnum;
				break;
			}
		}
		return returnValue;
	}
	
	/**
	 * Gets the initiate enum ignoring the case.
	 *
	 * @param value the value
	 * @return the MemGetEnum enum
	 */
	public static OrgEnum getInitiateEnumIgnoreCase(final String value) {
		OrgEnum returnValue = DEFAULT;
		String ignoreCase = value.toUpperCase();
		for (OrgEnum orgEnum : values()) {
			if (orgEnum.value.equals(ignoreCase)) {
				returnValue = orgEnum;
				break;
			}
		}
		return returnValue;
	}
}
